### ISSUE TITLE
Problem with 7.6.2

### ISSUE THREAD

**Issue by ssingwork** [WASdev/sample.dashboards#12]
Does it work with ES 7.6.2 ?  I am running the same version of Logstash and Filebeat and getting the following error.

[2020-05-05T22:47:27,401][WARN ][io.netty.channel.DefaultChannelPipeline][main] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: org.logstash.beats.InvalidFrameProtocolException: Invalid version of beats protocol: -1

**Comment by halim-lee** [comment]
Hi, which dashboards have you tried using?

**Comment by halim-lee** [comment]
The error log seems like it's suggesting there can be a misconfiguration between logstash and filebeat.
The link below might be helpful for your fix:
https://discuss.elastic.co/t/logstash-an-exceptioncaught-event-was-fired-and-it-reached-at-the-tail-of-the-pipeline-it-usually-means-the-last-handler-in-the-pipeline-did-not-handle-the-exception/180515

**Comment by ssingwork** [comment]
Thanks for reply.  I will try another instance
